// Objective-C API for talking to github.com/cbeuw/Cloak/Android Go package.
//   gobind -lang=objc github.com/cbeuw/Cloak/Android
//
// File is generated by gobind. Do not edit.

#ifndef __Cloak_outline_H__
#define __Cloak_outline_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Cloak_outlineOutlineDevice;

@interface Cloak_outlineOutlineDevice : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)transportConfig;
// skipped field OutlineDevice.IPDevice with unsupported type: github.com/Jigsaw-Code/outline-sdk/network.IPDevice

- (BOOL)close:(NSError* _Nullable* _Nullable)error;
// skipped method OutlineDevice.GetServerIP with unsupported parameter or return types

- (long)mtu;
- (NSData* _Nullable)read:(NSError* _Nullable* _Nullable)error;
- (BOOL)refresh:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)buf ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT Cloak_outlineOutlineDevice* _Nullable Cloak_outlineNewOutlineDevice(NSString* _Nullable transportConfig, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void Cloak_outlineStartAgain(void);

FOUNDATION_EXPORT void Cloak_outlineStartCloakClient(NSString* _Nullable localHost, NSString* _Nullable localPort, NSString* _Nullable config, BOOL udp);

FOUNDATION_EXPORT void Cloak_outlineStopCloak(void);

#endif
